window.collection = [
	'Universetocat',
	'Parentocats',
	'Yogitocat',
	'OctoAsians',
	'Octoqueer',
	'Octonaut',
	'Terracottocat',
	'Octogatos',
	'Adacats',
	'Surftocat',
	'Hulatocat',
	'Scubatocat',
	'Vinyltocat',
	'Snowtocat',
	'Blacktocats',
	'Dinotocat',
	'Benjamin Bannekat',
	'Skatetocat',
	'Inflatocat',
	'Filmtocat',
	'Private Investocat',
	'Jetpacktocat',
	'Luchadortocat',
	'Saritocat',
	'Yaktocat',
	'Labtocat',
	'Femalecodertocat',
	'Founding Father v2',
	'Mardigrastocat',
	'Kimonotocat',
	'professortocat_v2',
	'Robotocat',
	'Momtocat',
	'Snow Octocat',
	'Codercat',
	'Dojocat',
	'Octocat De Los Muertos',
	'Father Timeout',
	'Oktobercat',
	'Poptocat',
	'Cherryontop-o-cat',
	'Collabocats',
	'Hubot',
	'Benevocats',
	'Class Act',
	'Original',
]
